dist: xenial
sudo: true
language: python
python:
  - '3.7'
before_install:
  - sudo apt-get update
  - sudo apt-get install libev-dev -y
  - sudo apt-get install libuv-dev -y
install:
  - pip install -r requirements.txt
script:
  - pytest --cov=event_loop
after_success:
  - coveralls
notifications:
  -email: false
