dist: xenial
sudo: true
language: python
python:
  - '3.7'
before_install:
  - sudo apt install libev-dev -y
  - sudo apt install libuv-dev -y
install:
  - pip install -r requirements.txt
script:
  - pytest
notifications:
  -email: false
